/*
    ATM Cash Forecasting & Replenishment Management System
    01_Schema.sql — SQL Server schema for the domain tables.

    Notes:
    - Users / Roles / UserRoles / UserClaims / RoleClaims / UserLogins / UserTokens are owned by
      ASP.NET Core Identity (AspNetUsers, AspNetRoles, ...) and are generated by EF Core migrations
      (`dotnet ef migrations add InitialCreate` against ATMCashForecasting.Infrastructure). They are
      not hand-scripted here to avoid drifting from the Identity schema version in use.
    - This script is idempotent (CREATE TABLE ... guarded by OBJECT_ID checks) so it can be re-run
      safely against an existing database.
    - Run 02_StoredProcedures.sql, 03_Views.sql and 04_SeedData.sql after this script.
*/

SET NOCOUNT ON;
GO

IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'AtmCashForecasting')
BEGIN
    PRINT 'Run this script against an existing AtmCashForecasting database (create it via `dotnet ef database update` or CREATE DATABASE first).';
END
GO

-- =========================================================================================
-- Fine-grained module-level permissions, bridged to AspNetRoles (Module 1: RBAC).
-- =========================================================================================
IF OBJECT_ID('dbo.Permissions', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Permissions
    (
        Id          INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Permissions PRIMARY KEY,
        [Name]      NVARCHAR(100)     NOT NULL,
        [Module]    NVARCHAR(100)     NOT NULL,
        Description NVARCHAR(300)     NULL,
        CONSTRAINT UQ_Permissions_Name UNIQUE ([Name])
    );
END
GO

IF OBJECT_ID('dbo.RolePermissions', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.RolePermissions
    (
        RoleId       INT NOT NULL,           -- FK to AspNetRoles.Id (added once Identity tables exist)
        PermissionId INT NOT NULL CONSTRAINT FK_RolePermissions_Permissions REFERENCES dbo.Permissions(Id),
        CONSTRAINT PK_RolePermissions PRIMARY KEY (RoleId, PermissionId)
    );
END
GO

-- =========================================================================================
-- Master data
-- =========================================================================================
IF OBJECT_ID('dbo.Regions', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Regions
    (
        Id                   INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Regions PRIMARY KEY,
        RegionCode           NVARCHAR(20)   NOT NULL,
        RegionName           NVARCHAR(100)  NOT NULL,
        RegionalManagerUserId INT           NULL,
        CreatedAtUtc         DATETIME2      NOT NULL CONSTRAINT DF_Regions_CreatedAtUtc DEFAULT (SYSUTCDATETIME()),
        CreatedBy            NVARCHAR(450)  NULL,
        ModifiedAtUtc        DATETIME2      NULL,
        ModifiedBy           NVARCHAR(450)  NULL,
        IsDeleted            BIT            NOT NULL CONSTRAINT DF_Regions_IsDeleted DEFAULT (0),
        CONSTRAINT UQ_Regions_RegionCode UNIQUE (RegionCode)
    );
END
GO

IF OBJECT_ID('dbo.Branches', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Branches
    (
        Id                  INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Branches PRIMARY KEY,
        BranchCode          NVARCHAR(20)   NOT NULL,
        BranchName          NVARCHAR(150)  NOT NULL,
        RegionId            INT            NOT NULL CONSTRAINT FK_Branches_Regions REFERENCES dbo.Regions(Id),
        BranchManagerUserId INT            NULL,
        Address             NVARCHAR(300)  NULL,
        CreatedAtUtc        DATETIME2      NOT NULL CONSTRAINT DF_Branches_CreatedAtUtc DEFAULT (SYSUTCDATETIME()),
        CreatedBy           NVARCHAR(450)  NULL,
        ModifiedAtUtc       DATETIME2      NULL,
        ModifiedBy          NVARCHAR(450)  NULL,
        IsDeleted           BIT            NOT NULL CONSTRAINT DF_Branches_IsDeleted DEFAULT (0),
        CONSTRAINT UQ_Branches_BranchCode UNIQUE (BranchCode)
    );
    CREATE INDEX IX_Branches_RegionId ON dbo.Branches(RegionId);
END
GO

IF OBJECT_ID('dbo.AtmMaster', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.AtmMaster
    (
        Id                 INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_AtmMaster PRIMARY KEY,
        AtmCode            NVARCHAR(20)    NOT NULL,
        AtmName            NVARCHAR(150)   NOT NULL,
        TerminalId         NVARCHAR(30)    NOT NULL,
        RegionId           INT             NOT NULL CONSTRAINT FK_AtmMaster_Regions REFERENCES dbo.Regions(Id),
        BranchId           INT             NOT NULL CONSTRAINT FK_AtmMaster_Branches REFERENCES dbo.Branches(Id),
        Latitude           DECIMAL(9,6)    NOT NULL,
        Longitude          DECIMAL(9,6)    NOT NULL,
        AtmType            TINYINT         NOT NULL, -- 1 OnSite,2 OffSite,3 ThroughTheWall,4 MobileAtm,5 CashRecycler
        Currency           CHAR(3)         NOT NULL,
        Capacity           DECIMAL(18,2)   NOT NULL CONSTRAINT CK_AtmMaster_Capacity CHECK (Capacity >= 0),
        SafetyBufferAmount DECIMAL(18,2)   NOT NULL CONSTRAINT CK_AtmMaster_SafetyBuffer CHECK (SafetyBufferAmount >= 0),
        [Status]           TINYINT         NOT NULL, -- 1 Active,2 Inactive,3 Offline,4 UnderMaintenance,5 Decommissioned
        InstalledDate      DATE            NULL,
        DecommissionedDate DATE            NULL,
        CreatedAtUtc       DATETIME2       NOT NULL CONSTRAINT DF_AtmMaster_CreatedAtUtc DEFAULT (SYSUTCDATETIME()),
        CreatedBy          NVARCHAR(450)   NULL,
        ModifiedAtUtc      DATETIME2       NULL,
        ModifiedBy         NVARCHAR(450)   NULL,
        IsDeleted          BIT             NOT NULL CONSTRAINT DF_AtmMaster_IsDeleted DEFAULT (0),
        CONSTRAINT UQ_AtmMaster_AtmCode UNIQUE (AtmCode),
        CONSTRAINT UQ_AtmMaster_TerminalId UNIQUE (TerminalId)
    );
    CREATE INDEX IX_AtmMaster_Region_Branch ON dbo.AtmMaster(RegionId, BranchId);
    CREATE INDEX IX_AtmMaster_Status ON dbo.AtmMaster([Status]);
END
GO

IF OBJECT_ID('dbo.HolidayMaster', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.HolidayMaster
    (
        Id                INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_HolidayMaster PRIMARY KEY,
        HolidayDate       DATE          NOT NULL,
        HolidayName       NVARCHAR(150) NOT NULL,
        RegionId          INT           NULL CONSTRAINT FK_HolidayMaster_Regions REFERENCES dbo.Regions(Id),
        DemandUpliftFactor DECIMAL(5,2) NOT NULL CONSTRAINT DF_HolidayMaster_Uplift DEFAULT (1.0),
        CreatedAtUtc      DATETIME2     NOT NULL CONSTRAINT DF_HolidayMaster_CreatedAtUtc DEFAULT (SYSUTCDATETIME()),
        IsDeleted         BIT           NOT NULL CONSTRAINT DF_HolidayMaster_IsDeleted DEFAULT (0)
    );
    CREATE INDEX IX_HolidayMaster_Date_Region ON dbo.HolidayMaster(HolidayDate, RegionId);
END
GO

-- =========================================================================================
-- Transactional data
-- =========================================================================================
IF OBJECT_ID('dbo.AtmTransactions', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.AtmTransactions
    (
        Id                INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_AtmTransactions PRIMARY KEY,
        AtmId             INT            NOT NULL CONSTRAINT FK_AtmTransactions_AtmMaster REFERENCES dbo.AtmMaster(Id),
        TransactionDate   DATE           NOT NULL,
        WithdrawalCount   INT            NOT NULL CONSTRAINT CK_AtmTransactions_WithdrawalCount CHECK (WithdrawalCount >= 0),
        WithdrawalAmount  DECIMAL(18,2)  NOT NULL CONSTRAINT CK_AtmTransactions_WithdrawalAmount CHECK (WithdrawalAmount >= 0),
        DepositAmount     DECIMAL(18,2)  NOT NULL CONSTRAINT CK_AtmTransactions_DepositAmount CHECK (DepositAmount >= 0),
        RemainingCash     DECIMAL(18,2)  NOT NULL CONSTRAINT CK_AtmTransactions_RemainingCash CHECK (RemainingCash >= 0),
        CashLoaded        DECIMAL(18,2)  NOT NULL CONSTRAINT CK_AtmTransactions_CashLoaded CHECK (CashLoaded >= 0),
        [Source]          TINYINT        NOT NULL, -- 1 CsvUpload,2 ExcelUpload,3 ApiIntegration,4 ScheduledImport
        ValidationStatus  TINYINT        NOT NULL CONSTRAINT DF_AtmTransactions_ValidationStatus DEFAULT (1),
        ValidationNotes   NVARCHAR(500)  NULL,
        ImportBatchId     UNIQUEIDENTIFIER NOT NULL,
        CreatedAtUtc      DATETIME2      NOT NULL CONSTRAINT DF_AtmTransactions_CreatedAtUtc DEFAULT (SYSUTCDATETIME()),
        CreatedBy         NVARCHAR(450)  NULL,
        ModifiedAtUtc     DATETIME2      NULL,
        ModifiedBy        NVARCHAR(450)  NULL,
        IsDeleted         BIT            NOT NULL CONSTRAINT DF_AtmTransactions_IsDeleted DEFAULT (0),
        CONSTRAINT UQ_AtmTransactions_Atm_Date UNIQUE (AtmId, TransactionDate)
    );
    CREATE INDEX IX_AtmTransactions_ImportBatchId ON dbo.AtmTransactions(ImportBatchId);
    CREATE INDEX IX_AtmTransactions_Atm_Date ON dbo.AtmTransactions(AtmId, TransactionDate DESC);
END
GO

IF OBJECT_ID('dbo.AtmStatusHistory', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.AtmStatusHistory
    (
        Id             INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_AtmStatusHistory PRIMARY KEY,
        AtmId          INT           NOT NULL CONSTRAINT FK_AtmStatusHistory_AtmMaster REFERENCES dbo.AtmMaster(Id),
        PreviousStatus TINYINT       NOT NULL,
        NewStatus      TINYINT       NOT NULL,
        ChangedAtUtc   DATETIME2     NOT NULL CONSTRAINT DF_AtmStatusHistory_ChangedAtUtc DEFAULT (SYSUTCDATETIME()),
        Reason         NVARCHAR(300) NULL,
        CreatedAtUtc   DATETIME2     NOT NULL CONSTRAINT DF_AtmStatusHistory_CreatedAtUtc DEFAULT (SYSUTCDATETIME()),
        IsDeleted      BIT           NOT NULL CONSTRAINT DF_AtmStatusHistory_IsDeleted DEFAULT (0)
    );
    CREATE INDEX IX_AtmStatusHistory_Atm_Changed ON dbo.AtmStatusHistory(AtmId, ChangedAtUtc DESC);
END
GO

IF OBJECT_ID('dbo.ForecastResults', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ForecastResults
    (
        Id                          INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ForecastResults PRIMARY KEY,
        AtmId                       INT            NOT NULL CONSTRAINT FK_ForecastResults_AtmMaster REFERENCES dbo.AtmMaster(Id),
        ForecastRunId               UNIQUEIDENTIFIER NOT NULL,
        RunAtUtc                    DATETIME2      NOT NULL,
        Method                      TINYINT        NOT NULL, -- 1 MA,2 WMA,3 Trend,4 Seasonal,5 MLNet,6 Prophet,7 XGBoost,8 LSTM
        Horizon                     TINYINT        NOT NULL, -- 1,3,7,15,30 (days)
        TargetDate                  DATE           NOT NULL,
        ForecastedWithdrawalAmount  DECIMAL(18,2)  NOT NULL,
        ConfidenceScore             DECIMAL(5,2)   NOT NULL CONSTRAINT CK_ForecastResults_Confidence CHECK (ConfidenceScore BETWEEN 0 AND 1),
        LowerBound                  DECIMAL(18,2)  NULL,
        UpperBound                  DECIMAL(18,2)  NULL,
        ActualWithdrawalAmount      DECIMAL(18,2)  NULL,
        AbsolutePercentageError     DECIMAL(9,4)   NULL,
        CreatedAtUtc                DATETIME2      NOT NULL CONSTRAINT DF_ForecastResults_CreatedAtUtc DEFAULT (SYSUTCDATETIME()),
        IsDeleted                   BIT            NOT NULL CONSTRAINT DF_ForecastResults_IsDeleted DEFAULT (0)
    );
    CREATE INDEX IX_ForecastResults_Atm_Target ON dbo.ForecastResults(AtmId, TargetDate);
    CREATE INDEX IX_ForecastResults_RunId ON dbo.ForecastResults(ForecastRunId);
END
GO

IF OBJECT_ID('dbo.ForecastHistory', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ForecastHistory
    (
        Id                          BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ForecastHistory PRIMARY KEY,
        AtmId                       INT            NOT NULL CONSTRAINT FK_ForecastHistory_AtmMaster REFERENCES dbo.AtmMaster(Id),
        ForecastRunId               UNIQUEIDENTIFIER NOT NULL,
        RunAtUtc                    DATETIME2      NOT NULL,
        Method                      TINYINT        NOT NULL,
        Horizon                     TINYINT        NOT NULL,
        TargetDate                  DATE           NOT NULL,
        ForecastedWithdrawalAmount  DECIMAL(18,2)  NOT NULL,
        ConfidenceScore             DECIMAL(5,2)   NOT NULL,
        ActualWithdrawalAmount      DECIMAL(18,2)  NULL,
        AbsolutePercentageError     DECIMAL(9,4)   NULL,
        CreatedAtUtc                DATETIME2      NOT NULL CONSTRAINT DF_ForecastHistory_CreatedAtUtc DEFAULT (SYSUTCDATETIME())
    );
    CREATE INDEX IX_ForecastHistory_Atm_Target ON dbo.ForecastHistory(AtmId, TargetDate);
    CREATE INDEX IX_ForecastHistory_RunId ON dbo.ForecastHistory(ForecastRunId);
END
GO

IF OBJECT_ID('dbo.ReplenishmentRecommendations', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ReplenishmentRecommendations
    (
        Id                    INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ReplenishmentRecommendations PRIMARY KEY,
        AtmId                 INT           NOT NULL CONSTRAINT FK_ReplRec_AtmMaster REFERENCES dbo.AtmMaster(Id),
        ForecastResultId      INT           NOT NULL CONSTRAINT FK_ReplRec_ForecastResults REFERENCES dbo.ForecastResults(Id),
        GeneratedAtUtc        DATETIME2     NOT NULL CONSTRAINT DF_ReplRec_GeneratedAtUtc DEFAULT (SYSUTCDATETIME()),
        CurrentCash           DECIMAL(18,2) NOT NULL,
        ForecastDemand        DECIMAL(18,2) NOT NULL,
        SafetyBuffer          DECIMAL(18,2) NOT NULL,
        AtmCapacity           DECIMAL(18,2) NOT NULL,
        RecommendedLoadAmount DECIMAL(18,2) NOT NULL CONSTRAINT CK_ReplRec_LoadNonNegative CHECK (RecommendedLoadAmount >= 0),
        Priority              TINYINT       NOT NULL, -- 1 Routine,2 Scheduled,3 Urgent,4 Emergency
        ProjectedDepletionDate DATE         NOT NULL,
        RiskLevel             TINYINT       NOT NULL, -- 1 Low,2 Medium,3 High,4 Critical
        IsFulfilled           BIT           NOT NULL CONSTRAINT DF_ReplRec_IsFulfilled DEFAULT (0),
        FulfilledByCashLoadId INT           NULL,
        CreatedAtUtc          DATETIME2     NOT NULL CONSTRAINT DF_ReplRec_CreatedAtUtc DEFAULT (SYSUTCDATETIME()),
        IsDeleted             BIT           NOT NULL CONSTRAINT DF_ReplRec_IsDeleted DEFAULT (0)
    );
    CREATE INDEX IX_ReplRec_Atm_Fulfilled ON dbo.ReplenishmentRecommendations(AtmId, IsFulfilled);
    CREATE INDEX IX_ReplRec_RiskLevel ON dbo.ReplenishmentRecommendations(RiskLevel);
END
GO

IF OBJECT_ID('dbo.AtmCashLoads', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.AtmCashLoads
    (
        Id               INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_AtmCashLoads PRIMARY KEY,
        AtmId            INT           NOT NULL CONSTRAINT FK_AtmCashLoads_AtmMaster REFERENCES dbo.AtmMaster(Id),
        LoadDateUtc      DATETIME2     NOT NULL,
        AmountLoaded     DECIMAL(18,2) NOT NULL CONSTRAINT CK_AtmCashLoads_Amount CHECK (AmountLoaded >= 0),
        CashBeforeLoad   DECIMAL(18,2) NOT NULL,
        CashAfterLoad    DECIMAL(18,2) NOT NULL,
        Priority         TINYINT       NOT NULL,
        RecommendationId INT           NULL CONSTRAINT FK_AtmCashLoads_ReplRec REFERENCES dbo.ReplenishmentRecommendations(Id),
        LoadedByUserId   NVARCHAR(450) NULL,
        IsPlanned        BIT           NOT NULL CONSTRAINT DF_AtmCashLoads_IsPlanned DEFAULT (0),
        Notes            NVARCHAR(500) NULL,
        CreatedAtUtc     DATETIME2     NOT NULL CONSTRAINT DF_AtmCashLoads_CreatedAtUtc DEFAULT (SYSUTCDATETIME()),
        CreatedBy        NVARCHAR(450) NULL,
        IsDeleted        BIT           NOT NULL CONSTRAINT DF_AtmCashLoads_IsDeleted DEFAULT (0)
    );
    CREATE INDEX IX_AtmCashLoads_Atm_Date ON dbo.AtmCashLoads(AtmId, LoadDateUtc DESC);

    ALTER TABLE dbo.ReplenishmentRecommendations
        ADD CONSTRAINT FK_ReplRec_FulfilledByCashLoad FOREIGN KEY (FulfilledByCashLoadId) REFERENCES dbo.AtmCashLoads(Id);
END
GO

-- =========================================================================================
-- Alerts & notifications
-- =========================================================================================
IF OBJECT_ID('dbo.Alerts', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Alerts
    (
        Id                    INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Alerts PRIMARY KEY,
        AtmId                 INT            NULL CONSTRAINT FK_Alerts_AtmMaster REFERENCES dbo.AtmMaster(Id),
        AlertType             TINYINT        NOT NULL, -- 1 CashDepletion,2 AtmOffline,3 ForecastFailure,4 DataImportFailure,5 LowConfidence,6 ReplenishmentOverdue
        Severity              TINYINT        NOT NULL, -- 1 Info,2 Warning,3 High,4 Critical
        [Status]              TINYINT        NOT NULL CONSTRAINT DF_Alerts_Status DEFAULT (1), -- 1 Open,2 Acknowledged,3 Resolved,4 Suppressed
        Title                 NVARCHAR(200)  NOT NULL,
        Message               NVARCHAR(1000) NOT NULL,
        TriggeredAtUtc        DATETIME2      NOT NULL CONSTRAINT DF_Alerts_TriggeredAtUtc DEFAULT (SYSUTCDATETIME()),
        AcknowledgedAtUtc     DATETIME2      NULL,
        AcknowledgedByUserId  NVARCHAR(450)  NULL,
        ResolvedAtUtc         DATETIME2      NULL,
        CreatedAtUtc          DATETIME2      NOT NULL CONSTRAINT DF_Alerts_CreatedAtUtc DEFAULT (SYSUTCDATETIME()),
        IsDeleted             BIT            NOT NULL CONSTRAINT DF_Alerts_IsDeleted DEFAULT (0)
    );
    CREATE INDEX IX_Alerts_Status_Severity ON dbo.Alerts([Status], Severity);
    CREATE INDEX IX_Alerts_TriggeredAtUtc ON dbo.Alerts(TriggeredAtUtc DESC);
END
GO

IF OBJECT_ID('dbo.NotificationLogs', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.NotificationLogs
    (
        Id           INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_NotificationLogs PRIMARY KEY,
        AlertId      INT           NOT NULL CONSTRAINT FK_NotificationLogs_Alerts REFERENCES dbo.Alerts(Id) ON DELETE CASCADE,
        Channel      TINYINT       NOT NULL, -- 1 Email,2 Sms,3 Teams,4 InApp
        Recipient    NVARCHAR(200) NOT NULL,
        [Status]     TINYINT       NOT NULL CONSTRAINT DF_NotificationLogs_Status DEFAULT (1), -- 1 Pending,2 Sent,3 Failed,4 Retried
        SentAtUtc    DATETIME2     NULL,
        RetryCount   INT           NOT NULL CONSTRAINT DF_NotificationLogs_RetryCount DEFAULT (0),
        ErrorMessage NVARCHAR(1000) NULL,
        CreatedAtUtc DATETIME2     NOT NULL CONSTRAINT DF_NotificationLogs_CreatedAtUtc DEFAULT (SYSUTCDATETIME()),
        IsDeleted    BIT           NOT NULL CONSTRAINT DF_NotificationLogs_IsDeleted DEFAULT (0)
    );
    CREATE INDEX IX_NotificationLogs_Status ON dbo.NotificationLogs([Status]);
END
GO

-- =========================================================================================
-- Audit (immutable — no UPDATE/DELETE permission should be granted to application roles)
-- =========================================================================================
IF OBJECT_ID('dbo.AuditLogs', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.AuditLogs
    (
        Id           BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_AuditLogs PRIMARY KEY,
        TimestampUtc DATETIME2      NOT NULL CONSTRAINT DF_AuditLogs_TimestampUtc DEFAULT (SYSUTCDATETIME()),
        UserId       NVARCHAR(450)  NULL,
        UserName     NVARCHAR(150)  NULL,
        Action       TINYINT        NOT NULL,
        EntityName   NVARCHAR(150)  NOT NULL,
        EntityId     NVARCHAR(100)  NULL,
        OldValues    NVARCHAR(MAX)  NULL,
        NewValues    NVARCHAR(MAX)  NULL,
        IpAddress    NVARCHAR(50)   NULL,
        UserAgent    NVARCHAR(300)  NULL,
        IsSuccess    BIT            NOT NULL CONSTRAINT DF_AuditLogs_IsSuccess DEFAULT (1),
        Details      NVARCHAR(MAX)  NULL
    );
    CREATE INDEX IX_AuditLogs_TimestampUtc ON dbo.AuditLogs(TimestampUtc DESC);
    CREATE INDEX IX_AuditLogs_Entity ON dbo.AuditLogs(EntityName, EntityId);
END
GO
